name: Release

on:
  push:
    # branches:
    #   - dev
    tags:
      - "v*.*.*"

jobs:
  windows-builder:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Try Checkout Github Pages Branch
        continue-on-error: true
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "documentation"
      - name: Checkout Dev Branch
        uses: actions/checkout@v2
        with:
          ref: "dev"
          path: "source"
      - name: Build FrontEnd
        run: |
          Set-Location -Path source
          Set-Location -Path erajs-frontend
          yarn
          yarn build
          Set-Location -Path ..
      - name: Build Desktop
        run: |
          Set-Location -Path source
          Set-Location -Path erajs-desktop
          yarn
          yarn build
          yarn run pack
          Set-Location -Path ..
      - name: Build Documentation
        run: |
          Set-Location -Path source
          Set-Location -Path erajs-docs
          yarn
          yarn run docs:build
          Set-Location -Path ..
      - name: Generate Web
        run: |
          Set-Location -Path source
          New-Item -Path Era.js-SDK-web -ItemType directory
          Copy-Item -Path erajs-sdk\* -Destination Era.js-SDK-web -Recurse
          Copy-Item -Path erajs-backend\erajs -Destination Era.js-SDK-web -Recurse
          Copy-Item -Path erajs-frontend\dist\* -Destination Era.js-SDK-web\erajs\www -Recurse
      - name: Generate Windows
        run: |
          Set-Location -Path source
          New-Item -Path Era.js-SDK-win-x64 -ItemType directory
          Copy-Item -Path Era.js-SDK-web\* -Destination Era.js-SDK-win-x64 -Recurse
          Copy-Item -Path erajs-desktop\build\win-unpacked\* -Destination Era.js-SDK-win-x64 -Recurse
      - name: Compress
        run: |
          Set-Location -Path source
          Compress-Archive -Path Era.js-SDK-web -DestinationPath Era.js-SDK-web.zip
          Compress-Archive -Path Era.js-SDK-win-x64 -DestinationPath Era.js-SDK-win-x64.zip
          Write-Output ${{ github.ref }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')  # Require a TAG
        with:
          # token: ${{ secrets.key }}
          files: |
            source\Era.js-SDK-web.zip
            source\Era.js-SDK-win-x64.zip
      - name: Generate Documentation
        run: |
          Copy-Item -Path source\erajs-docs\docs\.vitepress\dist -Destination documentation\dist -Recurse
      - name: Try Delete Old Version
        continue-on-error: true
        run: |
          Remove-Item -Path documentation\docs -Recurse
      - name: Rename
        run: |
          Rename-Item -Path documentation\dist -NewName documentation\docs
      - name: Push
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.key }}
          push-branch: "gh-pages"
          commit-message: "Auto Generate & Deploy"
          force-add: "true"
          files: ./documantation/*
          name: Miswanting
          email: ihex@foxmail.com
  # ubuntu-builder:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.8'
  #         architecture: 'x64'
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "16"
  #     - name: Checkout Dev Branch
  #       uses: actions/checkout@v2
  #       with:
  #         ref: "dev"
  #     - name: Commands
  #       run: |
  #         mkdir Era.js-SDK-linux-x64
